"""
Step 6 handoff (AUDIT.md post-training-prep session): runs the 4 non-v5-a
systems (v2, rules_in_prompt, v3b-fix, base) against the LOCKED 1,000-
trajectory Phase 4 eval set (evaluation/phase4_eval_set.json, generated by
generate_phase4_eval_set.py, seed=4321). None of these four require the new
v5-a adapter -- this was deliberately DEFERRED and NOT run during the
post-training-prep session itself, because v5-a training held the only GPU
at 23,258/24,564 MiB (100% utilization) the entire time this was written;
running a second 7B-model inference job concurrently would risk both OOM and
slowing training.

Run this the moment v5-a's tmux session reports training complete:

    python llm_finetuning/prerun_baselines_phase4.py

Loads the locked eval set (asserts its sha256 matches what's recorded in
docs/V5_STATE.json's post_training_prep key -- refuses to run silently
against a set that was somehow modified after locking), builds prompts from
each item's ctx/key_windows (identical to eval_real_stgt_output.py's
convention), batches all 4 systems' generation, and writes
evaluation/phase4_baselines_results.json.

Ground truth for scoring against these results should use
ground_truth_from_true_chain-equivalent fields already embedded in
phase4_eval_set.json's items (expected_threat/expected_intent/expected_action/
pair/has_ground_truth) -- scoring itself is not implemented in this file
(intentionally left to a follow-up eval script once v5-a's own numbers exist,
so v5-a and the baselines are scored with the exact same code path -- avoid
building two divergent scorers).
"""
from __future__ import annotations

import argparse
import gc
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(REPO / "llm_finetuning"))

from swarm_intent.llm.client import LocalHFClient  # noqa: E402
from swarm_intent.inference import build_llm_prompt  # noqa: E402
from swarm_intent import pipeline_v2  # noqa: E402

from baselines import load_rules_txt  # noqa: E402

BASE_MODEL = "Qwen/Qwen2.5-7B-Instruct"
V2_ADAPTER = "adapters/qwen-swarm-v2"
V3B_FIX_ADAPTER = "adapters/qwen-swarm-v3b-fix"
BATCH_SIZE = 8
EVAL_SET_PATH = REPO / "evaluation" / "phase4_eval_set.json"
OUT_PATH = REPO / "evaluation" / "phase4_baselines_results.json"


def load_locked_eval_set(expected_sha256: str | None = None) -> dict:
    payload_json = EVAL_SET_PATH.read_text()
    actual_sha256 = hashlib.sha256(payload_json.encode()).hexdigest()
    if expected_sha256 and actual_sha256 != expected_sha256:
        raise RuntimeError(
            f"phase4_eval_set.json sha256 mismatch: expected {expected_sha256} "
            f"(from docs/V5_STATE.json's lock record), got {actual_sha256} -- this file was "
            f"modified after being locked. Refusing to run against a set that isn't provably "
            f"fixed. Investigate before proceeding.")
    payload = json.loads(payload_json)
    print(f"loaded {payload['n_sequences']} sequences (seed={payload['seed']}), "
         f"sha256={actual_sha256}")
    return payload


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--expected-sha256", default=None,
                    help="if set, asserts phase4_eval_set.json's sha256 matches (see "
                         "docs/V5_STATE.json post_training_prep.phase4_eval_set_lock)")
    ap.add_argument("--base", default=BASE_MODEL)
    args = ap.parse_args()

    payload = load_locked_eval_set(args.expected_sha256)
    items = payload["items"]

    print("=== loading 4 model clients (v2, rules_in_prompt, v3b-fix, base) ===")
    base_client = LocalHFClient(args.base, adapter_path=None, temperature=0.3)
    rules_client = LocalHFClient(args.base, adapter_path=None, temperature=0.3, system_prompt=load_rules_txt())
    ft_client = LocalHFClient(args.base, adapter_path=str(REPO / V3B_FIX_ADAPTER), temperature=0.3)
    v2_client = LocalHFClient(args.base, adapter_path=str(REPO / V2_ADAPTER), temperature=0.3)

    prompts = [build_llm_prompt(pipeline_v2._preds_from_key_windows(it["key_windows"]), it["ctx"], {})
              for it in items]

    print("=== batched generation, 4 systems ===")
    results = {}
    for label, client in (("base", base_client), ("rules_in_prompt", rules_client),
                          ("v3b-fix", ft_client), ("v2", v2_client)):
        print(f"  {label} ...")
        raw = client.complete_batch(prompts, batch_size=BATCH_SIZE)
        results[label] = {it["name"]: a for it, a in zip(items, raw)}

    del base_client, rules_client, ft_client, v2_client
    gc.collect()
    import torch
    torch.cuda.empty_cache()

    OUT_PATH.write_text(json.dumps({
        "eval_set_sha256": hashlib.sha256(EVAL_SET_PATH.read_text().encode()).hexdigest(),
        "n_sequences": payload["n_sequences"], "results": results,
    }, indent=2))
    print(f"\nsaved {OUT_PATH}")


if __name__ == "__main__":
    main()
